In [1]:
import pandas as pd
from tkinter import Tk, filedialog
from IPython.display import display

root = Tk()
root.withdraw()  # Hide the empty Tkinter window

file_path = filedialog.askopenfilename(
    title="Attach Bid List",
    filetypes=[("Excel files", "*.xlsx")],
)

root.destroy()

if file_path:
    df = pd.read_excel(file_path)
    display(df)
else:
    print("No file selected.")

2026-09-24 18:49:29.744 python[91938:1226818] +[IMKClient subclass]: chose IMKClient_Modern
2026-09-24 18:49:30.314 python[91938:1226818] The class 'NSOpenPanel' overrides the method identifier.  This method is implemented by class 'NSWindow'

,Bid(s),Product Group,Material,Batch,Gauge,Width,Weight lbs,PIW,Translated Grade,Comment,...,Foreign Mat. Index,Defect code text 2,Defect code text 3,Defect code text 4,Unrestricted,Weight Kg,Th,Width Of Pieces,Length Of Pieces,Density
0,NaN,AL,AL-SEC,4404062540,0.023,44.895,22421,499.409734,CS Type B,NaN,...,T,1602 Missing Identity,9962 SPM CROP,NaN,10170,10170,0.593,1140.33,1960,0.0077
1,NaN,AL,AL-SEC,5302062370,0.024,48.113,44621,927.420863,CS Type B,NaN,...,T,808 Dents,NaN,NaN,20240,20240,0.613,1222.07,3539,0.0076
2,NaN,AL,AL-SEC,4404097940,0.039,63.803,22465,352.099431,HSLA 50,NaN,...,T,979 Coating Weight High,986 Jet Lines,NaN,10190,10190,0.988,1620.59,827,0.0077
3,NaN,AL,AL-SEC,4404115700,0.049,62.937,59193,940.511941,HSLA70,NaN,...,L,1803 Holes,823 Roll Marks,NaN,26850,26850,1.237,1598.59,1770,0.0077
4,NaN,AL,AL-SEC,4404106320,0.055,60.688,22332,367.980490,HSLA 50,NaN,...,T,NaN,NaN,NaN,10130,10130,1.388,1541.47,616,0.0077
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
849,NaN,HRP,HRP-SEC,2504413830,0.252,72.500,24275,334.827586,Structural Steel 36 Type 2,NaN,...,T,507 Oscillated,1404 Rust Surface,9936 Remarks,11011,11011,6.401,1841.50,119,0.0078
850,NaN,HRP,HRP-SEC,2504420890,0.311,60.420,45977,760.956637,Structural Steel 36 Type 2,NaN,...,T,9936 Remarks,506 Offset Lap OD,NaN,20855,20855,7.899,1534.67,222,0.0077
851,NaN,HRP,HRP-SEC,2504343710,0.407,60.620,51709,853.002309,HSLA 50,NaN,...,G,1002 Mechanical Props - Wait F,9936 Remarks,1003 Mechanical Props - Wait F,23455,23455,10.338,1539.75,190,0.0078
852,NaN,HRP,HRP-SEC,2504404760,0.621,60.630,45633,752.647204,HSLA 50,NaN,...,G,1804 Lamination,NaN,NaN,20699,20699,15.773,1540.00,110,0.0077
853,NaN,HRP,HRP-SEC,2504413490,1.010,72.380,53325,736.736668,HSLA 50,NaN,...,G,1802 Gouge,NaN,NaN,24188,24188,25.654,1838.45,65,0.0079

In [ ]:
import pandas as pd
import io
import ipywidgets as widgets
from IPython.display import display, clear_output

# Create the upload button and space below it for messages
upload = widgets.FileUpload(accept='.xlsx', multiple=False)
output = widgets.Output()

# Function to display success when upload
def confirm_upload(change):
    with output:
        clear_output()
        print("File attached.")

# Make upload button see the function
upload.observe(confirm_upload, names='value')

# Display button and space below 
display(upload, output)

FileUpload(value=(), accept='.xlsx', description='Upload')

Output()

In [8]:
# Extracts data from widget and make it a df
if upload.value:
    content = upload.value[0]['content']
    df = pd.read_excel(io.BytesIO(content))
    display(df)
else:
    print("No file attached yet.")

,Bid(s),Product Group,Material,Batch,Gauge,Width,Weight lbs,PIW,Translated Grade,Comment,...,Foreign Mat. Index,Defect code text 2,Defect code text 3,Defect code text 4,Unrestricted,Weight Kg,Th,Width Of Pieces,Length Of Pieces,Density
0,NaN,AL,AL-SEC,4404062540,0.023,44.895,22421,499.409734,CS Type B,NaN,...,T,1602 Missing Identity,9962 SPM CROP,NaN,10170,10170,0.593,1140.33,1960,0.0077
1,NaN,AL,AL-SEC,5302062370,0.024,48.113,44621,927.420863,CS Type B,NaN,...,T,808 Dents,NaN,NaN,20240,20240,0.613,1222.07,3539,0.0076
2,NaN,AL,AL-SEC,4404097940,0.039,63.803,22465,352.099431,HSLA 50,NaN,...,T,979 Coating Weight High,986 Jet Lines,NaN,10190,10190,0.988,1620.59,827,0.0077
3,NaN,AL,AL-SEC,4404115700,0.049,62.937,59193,940.511941,HSLA70,NaN,...,L,1803 Holes,823 Roll Marks,NaN,26850,26850,1.237,1598.59,1770,0.0077
4,NaN,AL,AL-SEC,4404106320,0.055,60.688,22332,367.980490,HSLA 50,NaN,...,T,NaN,NaN,NaN,10130,10130,1.388,1541.47,616,0.0077
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
849,NaN,HRP,HRP-SEC,2504413830,0.252,72.500,24275,334.827586,Structural Steel 36 Type 2,NaN,...,T,507 Oscillated,1404 Rust Surface,9936 Remarks,11011,11011,6.401,1841.50,119,0.0078
850,NaN,HRP,HRP-SEC,2504420890,0.311,60.420,45977,760.956637,Structural Steel 36 Type 2,NaN,...,T,9936 Remarks,506 Offset Lap OD,NaN,20855,20855,7.899,1534.67,222,0.0077
851,NaN,HRP,HRP-SEC,2504343710,0.407,60.620,51709,853.002309,HSLA 50,NaN,...,G,1002 Mechanical Props - Wait F,9936 Remarks,1003 Mechanical Props - Wait F,23455,23455,10.338,1539.75,190,0.0078
852,NaN,HRP,HRP-SEC,2504404760,0.621,60.630,45633,752.647204,HSLA 50,NaN,...,G,1804 Lamination,NaN,NaN,20699,20699,15.773,1540.00,110,0.0077
853,NaN,HRP,HRP-SEC,2504413490,1.010,72.380,53325,736.736668,HSLA 50,NaN,...,G,1802 Gouge,NaN,NaN,24188,24188,25.654,1838.45,65,0.0079